Working branch
DS219/spring-2023 pull request #1
Opened 2023-02-22 20:01 UTC by ksapru

2023-03-15 19:34 UTC, sallyom commented on sapru-krish.txt
> +Today's date is Feb 15th. The time is 4:11PM. This is for a class project for credit
this should be in the file assignments/feb-15/sapru-krish.txt

2023-03-15 19:35 UTC, sallyom requested changes
joke.sh and hello-world.py should be in `assignments/sapru-krish/` folder

2023-03-15 19:50 UTC, ksapru commented on sapru-krish.txt
> +Today's date is Feb 15th. The time is 4:11PM. This is for a class project for credit
Renamed the file to sapru-krish using the "mv sapru sapru-krish" command

2023-03-22 19:44 UTC, ksapru commented on sapru-krish.txt
> +Today's date is Feb 15th. The time is 4:11PM. This is for a class project for credit
Duplicate files deleted

2023-03-22 19:46 UTC, merged