added Dockerfile
DS219/spring-2023 pull request #15
Opened 2023-04-05 19:54 UTC by leannert

2023-04-26 02:21 UTC, sallyom commented on assignments/TONG/README.md
> +podman run -it --rm [image-name]
The `-it` in the `podman run` command isn't needed for this image to run.
Run `podman run --help` to see the info for the `-i --interactive` and `-t --tty`, they are necessary when  you need to interact with a running container (like playing tic tak to or if you want to use shell commands while the container is running)

2023-04-26 02:23 UTC, sallyom requested changes
Nice documentation! I left a comment, also, do you want to include the `Notes` file? We can go over these in class 4/25 :)

2023-04-26 02:58 UTC, leannert commented on assignments/TONG/README.md
> +podman run -it --rm [image-name]
I see! Thank you for letting me know :)

2023-04-26 03:01 UTC, leannert commented on assignments/TONG/README.md
> +podman run -it --rm [image-name]
As a response to the comment (change request) below, I do want to keep the `Notes` file for future use. I made these while I was figuring out how to run my image, and I found them very helpful.

2023-05-03 18:29 UTC, sallyom commented
LGTM!

2023-05-03 18:30 UTC, sallyom approved these changes
Nice work

2023-05-03 18:30 UTC, merged